version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: container_postgresql
    restart: always
    environment:
      POSTGRES_DB: db_shapeofyou
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: container_adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: container_postgresql
    ports:
      - "8090:8080"

volumes:
  postgres_data:
